---
- hosts: test
  tasks:
    - name: copy file from nodes 
      fetch: 
        src: /opt/node.txt
        dest: /opt
      ignore_errors: true
    - name: install tool tree in centos hosts 
      yum:
        name: tree
        state: present 
      when: ansible_distribution == "CentOS"
    - name: install tool tree in ubuntu hosts 
      apt:
        name: tree
        state: present 
      when: ansible_distribution == "Ubuntu"
